### ISSUE TITLE
unable to connect to node rabbit@rabbitmq: nodedown

### ISSUE THREAD

**Issue by nikophil** [smebberson/docker-alpine#87]
Hello,

i tried to use your container with docker-compose :

```yml
rabbitmq:
    image: smebberson/alpine-rabbitmq
    hostname: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
        - RABBITMQ_ENABLE_MANAGEMENT_PLUGIN=true
        - RABBITMQ_USER=guest
        - RABBITMQ_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
```

but whenever i'v found no way to connect to rabbitmq trhought php... and whenever i connect to the container, and try a "status", i got an error :

```
/ # rabbitmqctl status
Status of node rabbit@rabbitmq ...
Error: unable to connect to node rabbit@rabbitmq: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbitmq]

rabbit@rabbitmq:
  * connected to epmd (port 4369) on rabbitmq
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: hostname mismatch?
  * suggestion: is the cookie set correctly?
  * suggestion: is the Erlang distribution using TLS?

current node details:
- node name: 'rabbitmq-cli-34@rabbitmq'
- home dir: /root
- cookie hash: ixo/2Fe1uNQ6Am3pfIxF+A==
```

thanks for your help
